## @doc
##   aws elastic search configuration
network.publish_host: _ec2:privateIp_

# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288

discovery.zen.minimum_master_nodes: 1
discovery.zen.hosts_provider: ec2
discovery.ec2.host_type: private_ip

## The following options remains here for reference purpose
## They are define by elastic.sh during runtime
# discovery.ec2.endpoint: ec2.eu-west-1.amazonaws.com
